### ISSUE TITLE
Uploading empty .docx file makes colore crash

### ISSUE THREAD

**Issue by arekf** [ifad/colore#37]
To reproduce:
`touch test.docx`
And upload the file.

The issue lays here:
https://github.com/ifad/colore/blob/master/lib/document.rb#L193

We should `rescue nil` or `rescue 'text/plain'` when the content type cannot be read from the file.

**Comment by vjt** [comment]
Question is also whether we should accept 0 size uploads in the first place. I'd say we should reject them.

**Comment by arekf** [comment]
Thanks, @tagliala! 😃
